version: "3.8"

services:
  web:
    build: ./aibnb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./aiabnb/ :/usr/src/aiabnb
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
